### ISSUE TITLE
Plz provide the tools and instructions for processing the raw data, thanks!

### ISSUE THREAD

**Issue by LanduRi** [Hlings/AcroFOD#1]
It's a wonderful job. Plz provide the tools and instructions for processing the raw data.

**Comment by gaoypeng** [comment]
Sure. I'm preparing relevant codes and instructions.

**Comment by LanduRi** [comment]
> Sure. I'm preparing relevant codes and instructions.

Please also provide the code for domain-aware data augmentation, thx :)

**Comment by gaoypeng** [comment]
Hi. I have provided the tools for processing raw cityscapes to yolo-style dataset in ./tools/cityscpaes_to_yolo.py :). You can follow the instruction in the file to prepare the data.
The domain-aware data augmentation has been provided.
-- For image-level, please refer to ./utils/dataset.py. The image-level mix augmentation is the same as 'mosaic' and 'mixup' in implementations. I just mix the source data and limited target data into the same dataset to perform domain-mix augmentation (refer to ./data/city_and_foggy8_1.yaml).
-- For box-level, please refer to ./utils/copy_pastev3.py for more details.

Hope the above reply will deal with your issue :)

**Comment by LanduRi** [comment]
Ok, thank you very much for your reply! I still have some questions. In city_and_foggy8_1.yaml, what do A and B represent respectively? Is it a path like "path/cityscapes/images/train "? If so, what does [A, B] represent?

**Comment by LanduRi** [comment]
Is the code complete, including optimization and expansion? I conducted experiments on the cityscapes->foggycity, and the results did not match the mAP50 (41.1) in the paper. Could you give me some guidance on reproducing the experimental results of the paper? Thank you very much.

**Comment by LanduRi** [comment]
Is the code complete, including optimization and augmentation? I conducted experiments on the **Cityscapes->Foggycity**, and the results did not match the mAP50 (41.1) in the paper. Could you give me some guidance on reproducing the experimental results of the paper? Thank you very much.

**Comment by gaoypeng** [comment]
Sure, the code is complete.

Reproduce results:
1: Data preparation. You can see the visualizations to verify.
2: Training config. I guess the problem is the training config. I check the provided config in the readme and find some misleadings :(.
To reproduce mAP50 (41.1) on **C to F**, you can try the following config:
```bash
python train_MMD.py --img 640 --batch 12 --epochs 600 --data ./data/city_and_foggy8_3.yaml --cfg ./models/yolov5x.yaml --hyp ./data/hyp_aug/mm1.yaml --weights '' --name "test"
```
The changes are mainly in batch-size and data augmentation.

Batch-size: I found the detector is hard to converge on **C to F** with a normal batch-size like 16. A smaller batch-size from 8~12 will get better results.
Data augmentation: Empirically, the cross-domain mixup augmentation is very important to get better results on **C to F** (provided in mm1.yaml). You can check ablation studies in the main text of this paper.

Hope the above reply is helpful :).
I will also provide a more detailed instructions nowadays.

**Comment by LanduRi** [comment]
Thank you very much. I have reproduced the results.
I have one more question. There is no city_and_foggy8_**3**.yaml in ./data directory. Is it city_and_foggy8_**1**.yaml?

**Comment by LanduRi** [comment]
Thank you very much. I have reproduced the results.
I have some questions.
1. There is no city_and_foggy8_3.yaml in ./data directory. Is it city_and_foggy8_1.yaml?
2. Which version of **Yolov5** do you use?

**Comment by gaoypeng** [comment]
Q1: Yes. Just different names. I also provide the target image indexes of  **C to F** and **S to C**  in "./data/target_indexes.txt". 
Q2:  I use Yolov5-3.0. Using an advanced version of yolov5 like 6.0 may get better results.
