### ISSUE TITLE
Target Sample Size Variation for VIPeD → COCO Benchmark

### ISSUE THREAD

**Issue by saranadeem01** [Hlings/AcroFOD#20]
Hi,

I hope you’re doing well.  I truly appreciate the effort that went into sharing this open-source repo.

In the ablation study for the Synthetic-to-Real Benchmark (VIPeD → COCO dataset), it is mentioned to take 60 random images instead of 8. Could you please clarify the reasoning behind selecting a larger number of samples in this case?

Additionally, are we supposed to randomly select a different number of samples for different datasets, or is there a specific guideline for sample selection across datasets?

Many thanks!

**Comment by gaoypeng** [comment]
Hi Sara,

Thanks for your interest in my work! Sorry for the late reply due to travel during the Thanksgiving holiday.

1: I just set a proportion (~0.1%) for the COCO person dataset, since there is no previous benchmark on this scenario. You can also try 8 images.

2: Yes, I mostly do a random selection (refer to my provided scripts for sample selection).

3: Yes, it's also a problem I met. I checked the previous papers and they require the sampled data to have all 8 categories. Therefore, I first perform random sampling, then I slightly adjust the sampled data (exchange paired images and labels) to have 8 classes.
